### PR TITLE
Layout & score card

### PR DESCRIPTION
**Pull request by 318097**
The layout is adjusted
Player 1 score is updated in the scorecard

Screenshot from 2019-04-02 21-01-50

### CODE REVIEW

**Review by shivangg — COMMENTED** [review]
Make sure the PR gets the green tick before assigning review.

**Comment by 318097** [comment]
Screenshot from 2019-04-03 23-50-46

**Review by shivangg — COMMENTED** [review]
Keep the image in a folder.
Otherwise, LGTM.

**Review by hassan23 — COMMENTED** [review]
LGTM

**Comment by 318097** [comment]
Screenshot from 2019-04-05 08-55-42
This is the last update for this PR. If there are any changes required, I'll do it in next PR or feel free to try on your own.

**Comment by 318097** [comment]
@shivangg & @hassan23 Please approve & merge if it looks fine.

**Review by shivangg — APPROVED** [review]
LGTM

**Pull request merged**
